name: coastguard
channels:
  - fbriol
  - conda-forge
  - defaults
dependencies:
  - earthengine-api
  - geopandas
  - spyder
  - geemap
  - scikit-image
  - rasterio
  - seaborn
  - astropy
  - geopy
  - pyfes
  - motuclient
  - netcdf4
