name: coastguard
channels:
  - conda-forge
  - defaults
dependencies:
  - earthengine-api
  - geopandas
  - pandas=2.0.3
  - spyder=5.5.0
  - geemap
  - scikit-image
  - matplotlib
  - rasterio
  - seaborn
  - astropy
  - geopy
  - notebook
  - motuclient
  - netcdf4
