name: coastguard
channels:
  - fbriol
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - affine
  - aiohttp
  - aiosignal
  - alabaster
  - alsa-lib
  - anyio
  - aom
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - astroid
  - astropy
  - async-timeout
  - atomicwrites
  - attr
  - attrs
  - autopep8
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - binaryornot
  - black
  - bleach
  - blosc
  - boost-cpp
  - bqplot
  - branca
  - brotli
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cairo
  - certifi
  - cffi
  - cfitsio
  - cftime
  - chardet
  - charls
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - colour
  - comm
  - contourpy
  - cookiecutter
  - cryptography
  - curl
  - cycler
  - dav1d
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - diff-match-patch
  - docutils
  - earthengine-api
  - ee_extra
  - eerepr
  - entrypoints
  - exceptiongroup
  - expat
  - ffmpeg
  - ffmpeg-python
  - fftw
  - filelock
  - fiona
  - flake8
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freexl
  - frozenlist
  - future
  - gdal
  - gdown
  - geeadd
  - geemap
  - geocoder
  - geographiclib
  - geojson
  - geopandas
  - geopandas-base
  - geopy
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gnutls
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - httplib2
  - icu
  - idna
  - imagecodecs
  - imageio
  - imagesize
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - inflection
  - intervaltree
  - ipyevents
  - ipyfilechooser
  - ipykernel
  - ipyleaflet
  - ipython
  - ipython_genutils
  - ipytree
  - ipywidgets
  - isoduration
  - isort
  - jack
  - jaraco.classes
  - jedi
  - jeepney
  - jellyfish
  - jinja2
  - joblib
  - jpeg
  - json-c
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jxrlib
  - kealib
  - keyring
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lazy-object-proxy
  - lazy_loader
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcrc32c
  - libcups
  - libcurl
  - libdap4
  - libdb
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - libidn2
  - libkml
  - liblapack
  - libllvm14
  - libnetcdf
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - librttopo
  - libsndfile
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libtool
  - libudev1
  - libunistring
  - libuuid
  - libva
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - libzlib
  - libzopfli
  - logzero
  - lz4-c
  - mapclassify
  - markdown-it-py
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mdurl
  - mistune
  - more-itertools
  - motuclient
  - multidict
  - munch
  - munkres
  - mypy_extensions
  - mysql-common
  - mysql-libs
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - netcdf4
  - nettle
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - numpydoc
  - openh264
  - openjpeg
  - openssl
  - overrides
  - p11-kit
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pathspec
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - plotly
  - pluggy
  - ply
  - pooch
  - poppler
  - poppler-data
  - portaudio
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - pulseaudio
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pycrs
  - pydocstyle
  - pyerfa
  - pyfes
  - pyflakes
  - pygments
  - pylint
  - pyls-spyder
  - pyopenssl
  - pyparsing
  - pyperclip
  - pyproj
  - pyqt
  - pyqt5-sip
  - pyqtwebengine
  - pyshp
  - pysocks
  - python
  - python-box
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-server
  - python-slugify
  - python-tzdata
  - python_abi
  - pytoolconfig
  - pytz
  - pyu2f
  - pywavelets
  - pyxdg
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qstylizer
  - qt-main
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtconsole-base
  - qtpy
  - rasterio
  - ratelim
  - re2
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - rope
  - rpds-py
  - rsa
  - rtree
  - ruamel.yaml
  - ruamel.yaml.clib
  - sankee
  - scikit-image
  - scikit-learn
  - scipy
  - scooby
  - seaborn
  - seaborn-base
  - secretstorage
  - send2trash
  - setuptools
  - shapely
  - sip
  - six
  - snappy
  - sniffio
  - snowballstemmer
  - snuggs
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlite
  - statsmodels
  - svt-av1
  - tenacity
  - terminado
  - text-unidecode
  - textdistance
  - threadpoolctl
  - three-merge
  - tifffile
  - tiledb
  - tinycss2
  - tk
  - toml
  - tomli
  - tornado
  - tqdm
  - traitlets
  - traittypes
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzcode
  - tzdata
  - ujson
  - unicodedata2
  - uri-template
  - uriparser
  - uritemplate
  - urllib3
  - watchdog
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - whatthepatch
  - wheel
  - whitebox
  - whiteboxgui
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - x264
  - x265
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xerces-c
  - xorg-fixesproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xyzservices
  - xz
  - yaml
  - yapf
  - yarl
  - zeromq
  - zfp
  - zipp
  - zlib
  - zlib-ng
  - zstd
